calc/urls.py
from django.conf.urls import url

from . import views

app_name = 'calc'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<activity_id>[0-9]+)/activity/$', views.activity, name='activity')
]

creditcalc/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('calc.urls')),
    url(r'^admin/', admin.site.urls),
]

calc/models.py
import datetime

from django.db import models
from django.utils import timezone

class Activity(models.Model):
    Contact = 'Contact Time'
    Independent = 'Independent Learning'
    activity_type_choices = (
        (Contact, 'Contact Time'),
        (Independent, 'Independent Learning')
    )
    activity_type = models.CharField(max_length=200, choices=activity_type_choices, default=Contact)
    activity_name = models.CharField(max_length=200)
    activity_description = models.TextField()
    image = models.FileField(default='No activity image')
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.activity_name

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

calc/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse

from .models import Activity

def index(request):
    activity_list = Activity.objects.order_by('-pub_date')
    contact_time = Activity.objects.filter(activity_type__startswith='Contact')
    independent_time = Activity.objects.filter(activity_type__startswith='Independent Learning')
    if request.method == 'POST':
        credits = int(request.POST['credits'])
        credits_double = credits * 2
        credits_quadrupled = credits * 4
        weeks = int(request.POST['weeks'])
        hoursContactTotal = 0
        hoursIndependentTotal = 0
        for h in contact_time:
            if request.POST['hoursContact' + str(h.id)]:
                int_h = int(request.POST['hoursContact' + str(h.id)])
                hoursContactTotal += int_h
        for h in independent_time:
            if request.POST['hoursIndependent' + str(h.id)]:
                int_h2 = int(request.POST['hoursIndependent' + str(h.id)])
                hoursIndependentTotal += int_h2
        context = {'activity_list': activity_list, 'credits': credits, 'credits_double': credits_double, 'credits_quadrupled': credits_quadrupled, 'weeks': weeks, 'hoursContactTotal': hoursContactTotal, 'hoursIndependentTotal': hoursIndependentTotal}
        return render(request, 'calc/index.html', context)
    else:
        context = {'activity_list': activity_list}
        return render(request, 'calc/index.html', context)

def activity(request, activity_id):
    activity = get_object_or_404(Activity, pk=activity_id)
    return render(request, 'calc/activity.html', {'activity': activity})

calc/templates/calc/activity.html
<p><a href="{% url 'calc:index' %}">Go back to calculator</a></p>
<p>{{ activity.image }}</p>
<h1>{{ activity.activity_name }}</h1>
<p>{{ activity.activity_description|linebreaks }}</p>

calc/templates/calc/index.html
<h1>Course Credit Hour Calculator</h1>
<p>Fill in your course details below and then choose the course activities you want to use in your course by indicating the amount of weekly work required for each of your chosen activities.</p>

<h2>Course Details</h2>
<h3>Course Credits</h3>
<form method="post">
{% csrf_token %}
  <input type="radio" name="credits" id="1" value="1" />
  <label>1 credit</label> <br />
  <input type="radio" name="credits" id="2" value="2" />
  <label>2 credits</label><br />
  <input type="radio" name="credits" id="3" value="3" checked />
  <label>3 credits</label><br />
  <input type="radio" name="credits" id="4" value="4" />
  <label>4 credits</label><br />

<h3>Course Length</h3>
{% csrf_token %}
  <input type="radio" name="weeks" id="6" value="6" />
  <label>6 weeks</label> <br />
  <input type="radio" name="weeks" id="15" value="15" checked />
  <label>15 weeks</label><br />

<h2>Course Activities</h2>
<p>For each activity you would like to include in your course, indicate the number of hours each week the activity will require.</p>
<h3>Contact Time Activities</h3>
  {% for activity in activity_list %}
  {% if activity.activity_type == "Contact Time" %}
  <input type="text" size="2" maxlength="2" placeholder="0" name="hoursContact{{ activity.id }}" id="hoursContact{{ forloop.counter }}" />
  <label><a href="{% url 'calc:activity' activity.id %}">{{ activity.activity_name }}</a></label><br />
  {% endif %}
  {% endfor %}

<h3>Independent Learning Activities</h3>
  {% for activity in activity_list %}
  {% if activity.activity_type == "Independent Learning" %}
  <input type="text" size="2" maxlength="2" placeholder="0" name="hoursIndependent{{ activity.id }}" id="hoursIndependent{{ forloop.counter }}" />
  <label><a href="{% url 'calc:activity' activity.id %}">{{ activity.activity_name }}</a></label><br />
  {% endif %}
  {% endfor %}
  <input type="submit" value="Submit">
  </form>

  {% if request.method == 'POST' %}
<h2>Results</h2>
  {% if weeks == 15 %}
<h3>Contact Time Total Weekly Hours</h3>
  {% if hoursContactTotal == 0 or hoursContactTotal < credits %}
  <p>You still need some more contact time activities to meet credit hour requirements. In this case, you need {{ credits }} hours worth and you only have {{ hoursContactTotal }}. </p>
  {% else %}
  <p>Great job. You have the required amount of contact time activities for the number of course credit. You needed {{ credits }} hours and you came up with {{ hoursContactTotal }}. </p>
  {% endif %}
<h3>Independent Learning Total Weekly Hours</h3>
  {% if hoursIndependentTotal >= credits_double %}
  <p>Great job. You have the required amount of contact time activities for the number of course credit. You needed {{ credits_double }} hours and you came up with {{ hoursIndependentTotal }}. </p>
  {% else %}
  <p>You still need some more contact time activities to meet credit hour requirements. In this case, you need {{ credits_double }} hours worth and you only have {{ hoursIndependentTotal }}.  </p>
  {% endif %}

  {% else %}
  <h3>Contact Time Total Weekly Hours</h3>
    {% if hoursContactTotal == 0 or hoursContactTotal < credits_double %}
    <p>You still need some more contact time activities to meet credit hour requirements. In this case, you need {{ credits_double }} hours worth and you only have {{ hoursContactTotal }}.</p>
    {% else %}
    <p>Great job. You've have the required amount of contact time activities for the number of course credit. You needed {{ credits_double }} hours and you came up with {{ hoursContactTotal }}. </p>
    {% endif %}
  <h3>Independent Learning Total Weekly Hours</h3>
    {% if hoursIndependentTotal >= credits_quadrupled %}
    <p>Great job. You have the required amount of contact time activities for the number of course credit. You needed {{ credits_quadrupled }} hours and you came up with {{ hoursIndependentTotal }} </p>
    {% else %}
    <p>You still need some more contact time activities to meet credit hour requirements. In this case, you need {{ credits_quadrupled }} hours worth and you only  have {{ hoursIndependentTotal }}. </p>
    {% endif %}
  {% endif %}
  {% endif %}